# Generated by Django 4.2 on 2023-09-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=128, null=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=128, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=128, null=True, verbose_name='Last Name')),
                ('bio', models.CharField(max_length=128, null=True, verbose_name='Bio')),
                ('language_code', models.CharField(max_length=5, verbose_name='Language code')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
            options={
                'verbose_name': 'Bot user',
                'verbose_name_plural': 'Bot users',
            },
        ),
    ]
