# Generated by Django 4.2.2 on 2023-08-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="status",
            field=models.CharField(
                choices=[
                    ("WANT2READ", "Хочу читать"),
                    ("READING", "Читаю"),
                    ("READ", "Прочитал"),
                ],
                default="WANT2READ",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
