version: "3.9"

services:
  db:
    container_name: 'db'
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=myPassW0rD
      - POSTGRES_USER=postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    command: -p 5432
    networks:
      my_network:

    deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 1000M

  backend:
    container_name: 'backend'
    build:
      context: .
      dockerfile: Dockerfile
    #command: sh -c "python manage.py runserver 0.0.0.0:8000"
    command: ./scripts/gunicorn.sh
    #command: ./scripts/django.sh
    env_file:
      - .env
    networks:
      my_network:
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/code
      - ./media:/code/media
    
    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1000M

networks:
  my_network:
    driver: bridge


# volumes:
#   my_volume:
    