# Generated by Django 4.2 on 2023-05-27 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estableshments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="contacts",
        ),
        migrations.RemoveField(
            model_name="place",
            name="gps_location",
        ),
        migrations.AddField(
            model_name="contact",
            name="place",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="estableshments.place",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gpslocation",
            name="place",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="estableshments.place",
            ),
            preserve_default=False,
        ),
    ]
