# Generated by Django 4.2 on 2023-05-13 05:40

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        unique=True,
                        validators=[
                            users.models.digit_only,
                            django.core.validators.MinLengthValidator(10),
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=70,
                        null=True,
                        unique=True,
                        verbose_name="Почта",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        max_length=70, unique=True, verbose_name="Никнейм"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=70, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=512, null=True, verbose_name="Обо мне"
                    ),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Не указано"), (1, "Mужской"), (2, "Женский")],
                        default=0,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
        ),
    ]
