# Generated by Django 4.2 on 2023-05-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "ordering": ["title"],
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["title"],
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
            },
        ),
    ]
