# Generated by Django 4.2 on 2023-04-15 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="book",
            name="cover_type",
            field=models.CharField(
                default="Paper", max_length=25, verbose_name="Тип переплета"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publish_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Год публикации"
            ),
        ),
    ]
