# Generated by Django 4.2.2 on 2023-07-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("author", models.CharField(max_length=50, verbose_name="Автор")),
                ("publish_year", models.IntegerField(verbose_name="Год издания")),
                (
                    "publisher",
                    models.CharField(max_length=50, verbose_name="Издательство"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(verbose_name="Количество страниц"),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
                "ordering": ["name"],
            },
        ),
    ]
