# Generated by Django 4.2.2 on 2023-07-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Есть в наличие"),
        ),
    ]
