# Generated by Django 4.2.2 on 2023-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_author_alter_book_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "description",
                    models.TextField(max_length=512, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                related_name="books", to="demo.category", verbose_name="Категории"
            ),
        ),
    ]
