# Generated by Django 4.2.2 on 2023-08-09 03:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0005_contact"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="book",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
    ]
