# Generated by Django 4.2 on 2023-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=512, verbose_name="Описание"),
        ),
    ]
