# Generated by Django 4.2 on 2023-05-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, max_length=512, null=True, verbose_name="Описание"
            ),
        ),
    ]
