# Generated by Django 4.2 on 2023-05-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_alter_category_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Время создания"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="update_time",
            field=models.DateTimeField(auto_now=True, verbose_name="Время изменения"),
        ),
    ]
