# Generated by Django 4.2 on 2023-05-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_category_create_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title"],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
